import turtle
import time
pen=turtle.Turtle()
window=turtle.getscreen()
turtle.hideturtle()
pen.pen(pencolor="black",fillcolor="yellow")
pen.pensize(3)
pen.penup()
pen.goto(0,-150)
pen.pendown()
pen.begin_fill()
pen.circle(200)
pen.end_fill()

pen.fillcolor("white")
pen.penup()
pen.goto(-80,80)
pen.pendown()
pen.begin_fill()
pen.circle(40)
pen.end_fill()

pen.penup()
pen.goto(80,80)
pen.pendown()
pen.begin_fill()
pen.circle(40)
pen.end_fill()

pen.fillcolor("black")
pen.penup()
pen.goto(-80,80)
pen.pendown()
pen.begin_fill()
pen.circle(20)
pen.end_fill()

pen.fillcolor("black")
pen.penup()
pen.goto(80,80)
pen.pendown()
pen.begin_fill()
pen.circle(20)
pen.end_fill()

pen.penup()
pen.goto(0,0)
pen.pendown()
pen.fillcolor("green")
pen.begin_fill()
pen.goto(-20,-20)
pen.goto(0,40)
pen.goto(20,-20)
pen.goto(0,0)
pen.end_fill()


pen.penup()
pen.fillcolor("orange")
pen.goto(0,-60)
pen.pendown()
pen.begin_fill()
pen.goto(-60,-60)
pen.right(270)
for i in range(180):
    pen.backward(1)
    pen.left(1)
pen.goto(0,-60)
pen.end_fill()

pen.penup()
pen.fillcolor("white")
pen.goto(-20,-60)
pen.pendown()
pen.begin_fill()
pen.goto(-20,-80)
pen.goto(0,-80)
pen.goto(0,-60)
pen.end_fill()

pen.begin_fill()
pen.goto(20,-60)
pen.goto(20,-80)
pen.goto(0,-80)
pen.goto(0,-60)
pen.end_fill()

time.sleep(4)
